version: '3.7'

services:

  app:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always

  db:
    expose:
      - "5432"
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    restart: always
    # Mount an initialization script and the persistent postgresql data volume
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/postgresql/data
